# ACS 7.2.x values

externalPort: 443
externalProtocol: https
externalHost: acs.sgek.sduckdns.org
persistence:
  enabled: true
  storageClass:
    enabled: true
    name: efs-sc
    accessModes:
      - ReadWriteMany
global:
  alfrescoRegistryPullSecrets: docker-registry-secrets 
  elasticsearch:
    host: vpc-sgp-fgalf-acs-opensearch-gsjrw47vullqn2m2qrdsazwcze.ap-southeast-1.es.amazonaws.com
    port: 443
    protocol: https
    user: alfresco
    password: Th-sIs1t
repository:
  replicaCount: 0
  image:
    tag: 7.2.1
  licenseSecret: acslicense
  startupProbe:
    periodSeconds: 180
    failureThreshold: 10
  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 180
    timeoutSeconds: 10
    failureThreshold: 6
  livenessProbe:
    initialDelaySeconds: 130
    periodSeconds: 180
    timeoutSeconds: 10

ooiService:
  replicaCount: 1
  image:
    tag: 1.1.3

msTeamsService:
  replicaCount: 1
  image:
    tag: 1.1.0

transformrouter:
  replicaCount: 1
  image:
    tag: 2.0.0
  resources:
    requests:
      memory: "512Mi"
    limits:
      memory: "512Mi"
    
s3connector:
  enabled: false

pdfrenderer:
  replicaCount: 1
  image:
    tag: 2.5.7
  readinessProbe:
    initialDelaySeconds: 120
  livenessProbe:
    initialDelaySeconds: 60

imagemagick:
  replicaCount: 1
  image:
    tag: 2.5.7
  readinessProbe:
    initialDelaySeconds: 120
  livenessProbe:
    initialDelaySeconds: 60

libreoffice:
  replicaCount: 1
  image:
    tag: 2.5.7
  readinessProbe:
    initialDelaySeconds: 120
  livenessProbe:
    initialDelaySeconds: 60

tika:
  replicaCount: 1
  image:
    tag: 2.5.7

transformmisc:
  replicaCount: 1
  image:
    tag: 2.5.7
  readinessProbe:
    initialDelaySeconds: 60
  livenessProbe:
    initialDelaySeconds: 60

aiTransformer:
  replicaCount: 1
  image:
    tag: 1.4.2
  readinessProbe:
    initialDelaySeconds: 60
  livenessProbe:
    initialDelaySeconds: 60

filestore:
  replicaCount: 1
  image:
    tag: 0.16.1
  readinessProbe:
    initialDelaySeconds: 60
  livenessProbe:
    initialDelaySeconds: 60

share:
  image:
    tag: 7.2.1

alfresco-search:
  enabled: false
  searchServicesImage:
    tag: 2.0.4

alfresco-elasticsearch-connector:
  enabled: true
  liveIndexing:
    mediation:
      image:
        tag: 3.1.1
    content:
      image:
        tag: 3.1.1
    metadata:
      image:
        tag: 3.1.1
    path:
      image:
        tag: 3.1.1
  reindexing:
    enabled: true
    postgresql:
      url: jdbc:postgresql://alfrescodbv2-cluster.cluster-ccnwukvr3jmm.ap-southeast-1.rds.amazonaws.com:5432/

alfresco-digital-workspace:
  enabled: true
  image:
    tag: 3.0.0
  resources:
# https://github.com/aws/amazon-cloudwatch-agent/issues/580
# For Fargate the requests and limits MUST be the same.
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 1
      memory: 1024Mi

postgresql:
  enabled: false
  image:
    tag: 13.3.0

postgresql-syncservice:
  enabled: false
  image:
    tag: 13.3.0

database:
  external: true
  driver: org.postgresql.Driver
  url: jdbc:postgresql://alfrescodbv2-cluster.cluster-ccnwukvr3jmm.ap-southeast-1.rds.amazonaws.com:5432/
  user: alfresco
  password: alfresco
activemq:
  enabled: false  
alfresco-sync-service:
  syncservice:
    enabled: true
    image:
    tag: 3.7.3-A1
  messageBroker:
    url: ssl://b-de8b1b83-5ee2-4d5f-935b-aff21fd5d3d1-1.mq.ap-southeast-1.amazonaws.com:61617      
    user: alfresco
    password: beeisnotdctm
messageBroker: &acs_messageBroker
  url: ssl://b-de8b1b83-5ee2-4d5f-935b-aff21fd5d3d1-1.mq.ap-southeast-1.amazonaws.com:61617 
  user: alfresco
  password: beeisnotdctm
